FROM arm32v7/alpine:3.16@sha256:b1bf0a88958c558f15d3399612e5b4d3464fedfb62b15701255f1f9bbeb5253b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-yaml"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-yaml"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-yaml"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-yaml"

ADD dist/drone-yaml /bin/
ENTRYPOINT [ "/bin/drone-yaml" ]
