FROM arm32v7/alpine:3.15@sha256:8483ecd016885d8dba70426fda133c30466f661bb041490d525658f1aac73822

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-yaml"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-yaml"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-yaml"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-yaml"

ADD release/arm/drone-yaml /bin/
ENTRYPOINT [ "/bin/drone-yaml" ]
